[features]
seeds = false
[programs.localnet]
voting = "izyDVLDUCJuvrTokXBunuxNiiiT2CaBhyVJ7LavBhuY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nightingale/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
