[features]
seeds = false
[programs.localnet]
voting = "FQKeNb3XQQqGN7ULcMYbWsmppCmN2FKpkhb6ZJWhHFsi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nightingale/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
