[features]
seeds = false
[programs.localnet]
voting = "7EDCmRd14WTS9gGVJWhypz43wXp9bnkRgW3zxQzeCFMY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nightingale/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
