[features]
seeds = false
[programs.localnet]
voting = "9YC38kX1UhXPN6zBo4GuJHYTJ6rk9ucLxrdP4sj19rgc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nightingale/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
