[features]
seeds = false
[programs.localnet]
voting = "4JA7SFWdpchJETv26nhLCpWYYd5yoMG3Xy6zL8wMP6DL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/nightingale/.config/solana/id.json"

[scripts]
test = "yarn run mocha"
