# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Revolutionaries
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Revolutionaries

        # ID to load the MSP definition as
        ID: Revolutionaries

        MSPDir: ../../../data/rev/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Revolutionaries.admin', 'Revolutionaries.peer', 'Revolutionaries.client')"
            Writers:
                Type: Signature
                Rule: "OR('Revolutionaries.admin', 'Revolutionaries.client')"
            Admins:
                Type: Signature
                Rule: "OR('Revolutionaries.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Revolutionaries.peer')"
