# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Conservatives
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Conservatives

        # ID to load the MSP definition as
        ID: Conservatives

        MSPDir: ../../../data/con/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Conservatives.admin', 'Conservatives.peer', 'Conservatives.client')"
            Writers:
                Type: Signature
                Rule: "OR('Conservatives.admin', 'Conservatives.client')"
            Admins:
                Type: Signature
                Rule: "OR('Conservatives.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Conservatives.peer')"
